lib/parse.js
test/compress/template-string.js

fix return of template with trailing backslash

---

lib/compress.js
test/compress/collapse_vars.js

from https://github.com/mishoo/UglifyJS2/pull/3097
fixes #9

[cherry-pick] handle RHS side-effects in `collapse_vars`

---

lib/compress.js
test/compress/reduce_vars.js

[cherry-pick] fix escape analysis on `AST_New` (#3043)

---

README.md
lib/output.js
test/compress/issue-2989.js
test/run-tests.js

[cherry-pick] preserve case when `inline_script` (#2991)

---

lib/compress.js
test/compress/functions.js

[cherry-pick] fix corner case in `inline` (#3017)

---

lib/compress.js
test/compress/collapse_vars.js

[cherry-pick] fix `collapse_vars` within loops (#2915)

---

lib/compress.js
test/compress/properties.js

[cherry-pick] fix `join_vars` on property accessors (#2895)

---

test/compress/reduce_vars.js

No code changes - original optimization wasn't merged.

[cherry-pick] add expect_stdout tests from #3141

---

lib/compress.js
lib/mozilla-ast.js
lib/output.js
test/compress/regexp.js
test/compress/string-literal.js
test/input/spidermonkey/input.js

fix RegExp Literal in spidermonkey AST parse and output

---

lib/ast.js
lib/compress.js
lib/scope.js
test/compress/drop-unused.js

https://github.com/mishoo/UglifyJS2/pull/3147

port #3147: fix corner cases with `eval()`

---

test/compress/reduce_vars.js

https://github.com/mishoo/UglifyJS2/pull/3151
No fix necessary as optimization not present in `terser`.

add upstream test from #3151 - no code changes

---

test/fetch.js
test/jetstream.js

https://github.com/mishoo/UglifyJS2/pull/3165

[cherry-pick] update JetStream URL (#3165)

---

README.md
bin/uglifyjs
lib/ast.js
lib/minify.js
test/input/enclose/input.js
test/mocha/cli.js
test/mocha/minify.js

[cherry-pick] re-introduce `enclose` (#3163)

---

README.md

I just made a rollup plugin of this project.
https://github.com/TrySound/rollup-plugin-terser

Add rollup plugin link

---

lib/compress.js
test/compress/yield.js
test/mocha/cli.js

fix handling of `yield` in `collapse_vars`

---

lib/compress.js
test/compress/properties.js
test/mocha/unicode.js

[cherry-pick] fix corner cases in `properties`

---

lib/compress.js
test/compress/properties.js

fix class extends expression handling in `join_vars`

---

lib/ast.js
lib/mozilla-ast.js
lib/output.js
lib/parse.js
test/mocha/minify.js

also remove unused AST_RegExp.raw property
fixes #67

revert fafc6993 and add test for AST_RegExp.value.raw_source

---

lib/compress.js
test/compress/destructuring.js

fixes https://github.com/mishoo/UglifyJS2/issues/3205

fix function `inline` of destructuring declarations

---

lib/compress.js

refine function `inline` of destructuring declarations

---

lib/compress.js
test/compress/reduce_vars.js

https://github.com/mishoo/UglifyJS2/commit/5ffc17d4a

[port] fix corner case in `unused`

---

lib/output.js
test/mocha/minify.js
test/mocha/sourcemaps.js

add class literal support to source maps

---

lib/compress.js
test/compress/harmony.js

fix handling of default function parameters by `unused`

---

package.json

See: https://github.com/eslint/eslint-scope/issues/39

remove lint upon commit due to virus in eslint-scope

---

package.json

Reverts fabiosantoscode/terser#83
The issue has been [resolved](https://status.npmjs.org/incidents/dn7c1fgrr7ng)

Revert "remove lint upon commit due to virus in eslint-scope"

---

lib/output.js
lib/parse.js
test/compress/async.js

Fixes issue #97.
Thanks for the guidance @kzc!

Add support for async generator methods

---

lib/parse.js
test/compress/directives.js

fix parsing statement mistaken for a directive

---

lib/propmangle.js
test/compress/properties.js

have `mangle.properties` handle computed props and numeric keys

---

lib/compress.js
test/compress/destructuring.js

fix `unused` decl with side effect followed by destructuring decl

---

.travis.yml

Drop node 10 for node 11, since bugs will probably occur on both.

test node 11

---

package-lock.json
package.json
test/run-tests.js

This reverts commit 58d6d326c32d754d46db23a78b0dd25166030fd7.

Revert "speed tests up by parallelising them"

---

tools/node.js

to aid debugging of releases and local development

add TERSER_NO_BUNDLE=1 support to terser CLI

---

test/mocha/release.js

enable `test/jetstream.js` on node 10

---

lib/compress.js
test/compress/issue-t120.js

fixes `TypeError: Cannot read property '_walk' of null`
closes #120

fix `inline: 3` loop bug

---

lib/parse.js
lib/scope.js
test/compress/export.js
test/run-tests.js

fix mangle of import/export symbols with name cache

---

lib/compress.js
test/compress/drop-unused.js
test/run-tests.js

have `reduce_vars` and  `inline` respect `top_retain`

---

lib/compress.js
test/compress/reduce_vars.js

for arrays and object literals

fix corner case in `reduce_funcs`

---

lib/compress.js
test/compress/inline.js

fix function `inline` within class extends

---

lib/compress.js
test/compress/drop-unused.js

fix top_retain TypeError exception

---

lib/scope.js
test/compress/export.js
test/compress/issue-2001.js

mangle toplevel export default function and class names

---

.github/ISSUE_TEMPLATE.md
README.md

Add some notes about source-map-support module in our README and issue template.

notes about source-map-support

---

README.md

Fix a URL in README

---

package-lock.json
package.json
test/fuzz.js

11 issue have been identified where acorn is able parse input but terser fails and 10 issues for vice versa. These issue have been ignored so the fuzzer will run in an endless loop.

A new ES6 capable fuzzer based on eslump

---

lib/compress.js
test/compress/arrays.js
test/compress/functions.js
test/compress/harmony.js
test/compress/reduce_vars.js

I’m not confident about where things “should” be placed in compress.js, but other than that I think this is complete.
Fixes #221.

WIP: inline spread syntax

---

lib/compress.js
test/compress/block-scope.js

Recursively build list of variables names til AST_Toplevel reached

---

lib/compress.js
test/compress/evaluate.js

Fix for global hasOwnProperty when first argument is object

---

bin/uglifyjs
bin/uglifyjsnobundle
package-lock.json
package.json
test/input/config-file/1.js
test/input/config-file/2.js
test/input/config-file/cf.json
test/mocha/cli-2.js
test/mocha/cli.js
test/mocha/unicode.js

Added ability to list files in config

---

lib/compress.js
test/compress/array-constructor.js

Replace array constructor with literal when it's possible

---

.coveralls.yml
package-lock.json
package.json
test/input/spidermonkey/input.js

Removed deprecated istanbul and unused coveralls

---

lib/output.js
lib/parse.js
package-lock.json
package.json
test/compress/numbers.js

Compress numbers

---

main.js
test/node.js
test/ufuzz.js
tools/node.js

Command: `terser --help options`
*Actual:* `TypeError: UglifyJS.default_options is not a function`
*Expected:* Help message

Fixed help command

---

lib/compress/index.js
test/compress/block-scope.js

Refixed parent function parameters overshadowing

---

lib/compress/index.js
test/compress/block-scope.js
test/compress/hoist_props.js

Fixed corner case with var_names

---

README.md
lib/propmangle.js
test/compress/properties.js
test/mocha/glob.js
tools/terser.d.ts

Added ability to use pattern string as input for mangle-properties regex

---

lib/parse.js
lib/utils.js

As it supported by node 6+
Reference: https://node.green/#ES2015-functions-class

Redo custom errors with ES2015 classes

---

lib/compress/index.js

Got rid of regexp for checking first symbol.

Get rid of regexp for checking @

---

lib/sourcemap.js
test/mocha/input-sourcemaps.js

Reverts terser-js/terser#342
Closes #380

Revert "Fix compressed source-maps have non-terminated segments"

---

lib/compress/index.js
lib/output.js
lib/parse.js
lib/scope.js
lib/utils.js

I used native `Array.prototype.every` instaed of legacy helper.

Use array every instaed of all

---

lib/compress/index.js
lib/parse.js
lib/utils.js

I got rid of legacy `find_if` and used native `Array.prototype.some`, `Array.prototype.find` methods.

Use native Array's some find methods

---

lib/compress/index.js
test/compress/export.js

Fixed issue with producing broken code when minifying ESM

---

lib/ast.js
lib/compress/index.js
lib/mozilla-ast.js
lib/output.js
lib/parse.js
test/compress/big_int.js
test/compress/syntax-errors.js

Added support for BigInt

---

lib/ast.js

`Compress` and `TreeTransformer` have been already refactored and also they extends from TreeWalker. Now TreeWalker refactored in same style to be consistent :)

Refactored TreeWalker to ES6 class

---

lib/output.js
test/compress/comments.js
test/mocha/comments.js

This is a simple solution to fix #396, and has very little negative impact on speed.

check every comment token before printing it

---

bin/uglifyjs

Don't generate sourcemap if url = "inline"

---

lib/scope.js
test/compress/keep_names.js

This fix https://github.com/terser/terser/issues/191#issuecomment-540412889 .

fix some wrong logic about keep_fnames

---

README.md
bin/terser
lib/compress/index.js
lib/output.js
lib/parse.js
lib/utils/index.js
test/compress/arrow.js
test/compress/destructuring.js
test/compress/harmony.js
test/compress/issue-203.js
test/compress/object.js
test/compress/parameters.js
test/compress/properties.js
test/compress/try-catch.js
test/compress/unicode.js
test/mocha/function.js
test/mocha/object.js
test/mocha/spidermonkey.js
test/mocha/unicode.js
tools/terser.d.ts

feat: set ES version by year

---

README.md
lib/output.js
test/compress/numbers.js

Added output option to keep numbers as is

---

lib/ast.js
lib/output.js
lib/parse.js
lib/transform.js
test/mocha/class.js

WIP: Added support for class properties and static class properties

---

tools/terser.d.ts

Added a 'strict' value to keep_quoted type.

Add the 'strict' value to keep_quoted

---

lib/ast.js
lib/equivalent-to.js
lib/mozilla-ast.js
lib/output.js
lib/parse.js
lib/size.js
package-lock.json
package.json
test/compress/harmony.js
test/input/spidermonkey/input.js
test/mocha/spidermonkey.js

Fixes https://github.com/terser/terser/issues/761

support parsing import.meta

---

CONTRIBUTING.md

Fixed typo in `CONTRIBUTING.md`

docs(contributing): fix typo

---

README.md

This PR fixes two anchor links in the readme.

Fix mangle anchor links in the readme

---

lib/compress/inference.js

This fixes https://github.com/terser/terser/issues/1022#issue-937655494, though https://github.com/terser/terser/issues/1022#issuecomment-877641575 still exists.

fix: functions in global_defs may be compressed mistakenly

---

test/compress.js

I use this a lot when trying to isolate the output changes for a PR.

Add ability to grep for test compress test case

---

lib/ast.js
lib/minify.js
lib/parse.js
lib/propmangle.js
test/compress/mangleprops-mangleprop-annotation.js

extend `__MANGLE_PROP__` for object property access and assignment

---

tools/domprops.js

`roundRect` is a method on `CanvasRenderingContext2D`
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/roundRect
https://caniuse.com/mdn-api_canvasrenderingcontext2d_roundrect

Added roundRect to domprops.js

---

lib/compress/common.js
lib/compress/evaluate.js
test/compress/big_int.js

Not confident enough to release this right now because handling BigInt can cause a bunch of TypeErrors, both in Terser and output code.

Evaluate some BigInt operations
