lib/compress.js, test/compress/functions.js
=> [cherry-pick] fix AST corruption due to `collapse_vars` & `inline` (#2899)

lib/compress.js
=> [cherry-pick] improve performance when handling unused variables in `collapse_vars` (#3084)

README.md, lib/compress.js, lib/transform.js, test/compress/collapse_vars.js, test/compress/defaults.js, test/compress/functions.js, test/compress/hoist_props.js, test/compress/pure_funcs.js, test/compress/reduce_vars.js, test/input/defaults/input.js, test/mocha/cli.js, test/mocha/minify.js, test/run-tests.js
Note: generated code may be different from `uglify-js` as most optimization and feature PRs were not merged.
=> Merge upstream bug fixes to pass uglify-js v3.3.24 `expect_stdout` tests

test/compress/collapse_vars.js, test/compress/drop-unused.js, test/compress/evaluate.js, test/compress/functions.js, test/compress/hoist_props.js, test/compress/issue-1704.js, test/compress/issue-973.js, test/compress/loops.js, test/compress/properties.js, test/compress/pure_getters.js, test/compress/reduce_vars.js, test/compress/sequences.js, test/run-tests.js
Note: generated code may be suboptimal as optimizations not merged
* make test `expect`/`expect_exact` clauses optional when `expect_stdout` present
=> add expect_stdout tests from uglify-js without code changes

lib/minify.js, test/sourcemaps.js
ae6f08ba294e2785aaf5ff9d4be4dd857fede147 added the `'ascii'` parameter
to Buffer conversion functions `to_ascii` and `to_base64`. However
`to_ascii` didn't actually convert to ascii before, but to a utf8 string
(the default Buffer.toString behaviour). Passing in 'ascii' breaks
reading and writing valid inline source maps with unicode characters.
This patch removes the 'ascii' parameter so that the conversion uses
utf8 again. I would've filed this upstream but it didn't get merged into
uglify-js yet (only uglify-es, and thus terser).
Ref https://github.com/mishoo/UglifyJS2/pull/2947
=> Fix inline source maps containing unicode characters

README.md, lib/compress.js, test/compress/arguments.js, test/compress/drop-unused.js, test/ufuzz.json
https://github.com/mishoo/UglifyJS2/pull/3193
also take into account:
- parameter destructuring
- duplicate parameter names
disable compress option `arguments` by default
fixes #58
=> port uglify-js `arguments` compress option fix

.gitignore, bin/uglifyjs, lib/output.js, package-lock.json, package.json
- browser bundle works with JS bundlers as well as with
an HTML <script> tag using the global `Terser` variable.
- enable source map debug support for CLI with
TERSER_DEBUG=1 environment variable setting.
=> generate source map for browser bundle upon prepublish

lib/compress.js, test/compress/destructuring.js
=> drop `unused` destructuring declarations when `pure_getters` enabled

test/compress/parse_errors.js, test/run-tests.js
when the test `input` clause is a template string.
=> add ability to test parse errors with `expect_error`

README.md, lib/scope.js, test/compress/keep_names.js
Hey there 👋 
I want to only keep certain function and class names in my bundles so that our error reporting software will report errors correctly when calling `Function.prototype.name`. Setting `keep_fnames: true` adds too much unwanted data.
This PR allows users to pass a regular expression to `keep_fnames` and `keep_classnames` and will only mangle class names and functions that don't match that regular expression.
Maybe there are too much redundancy in the tests since I figure the `keep_fnames` and `keep_classnames` are already being testing somewhere else. Let me know I'll delete those tests and only keep the `keep_some_*` tests.
✨
=> Accept regex in mangle keep options

lib/compress.js, lib/scope.js, lib/utils.js, test/compress/keep_names.js
Use case:
```js
minify(code, { keep_fnames: /regex/ })
```
The regex gets forwarded to both `mangle` and `compress` options. Respecting the regex was implemented within `mangle`, but in other places the value was still treated like a boolean.
This resulted in functions which would otherwise be anonymized still having a name:
```js
a.map(function n() { ... })
```
where in fact the correct compression should have been:
```js
a.map(function() { ... })
```
Followup to #125 /cc @koddsson
=> Fix `keep_fnames` regex use in combination with `reduce_vars`

lib/compress.js, test/compress/issue-t120.js
improve the #152 fix for #120 
* up to 15% faster in some cases
* use shallow clone for value rather than deep clone
* no test regressions
=> more efficient fix for `inline: 3` loop bug

package.json, tools/node.d.ts, tools/terser.d.ts
I just added TS definitions to use it with TypeScript.
Definitions were copied from uglify-js.
=> Add TypeScript definitions

test/compress/evaluate.js, test/compress/reduce_vars.js, test/compress/string-literal.js, tools/colorless-console.js
Two commits here to make the tests compatible with Node.js 12 as well as prerelease versions of Node.js.
First, the output semantics of `console.log` for cases of non-string first argument will change which breaks a few output expectations in the tests. I made the tests compatible with any Node.js version by ensuring that the first argument is a string, in which case the output will be the same in all versions.
Additionally, the first commit makes the version check of `tools/colorless-console.js` compatible with prerelease versions of Node.js.
Related:
- https://github.com/nodejs/node/pull/23162
- https://github.com/nodejs/node/issues/25060
- https://github.com/mishoo/UglifyJS2/pull/3304
=> Make tests compatible with Node.js 12 and prerelease versions

.travis.yml, appveyor.yml, package.json, test/compress/arrow.js, test/compress/async.js, test/compress/collapse_vars.js, test/compress/dead-code.js, test/compress/functions.js, test/compress/harmony.js, test/compress/if_return.js, test/compress/node_version.js, test/compress/object.js, test/compress/properties.js, test/compress/reduce_vars.js, test/compress/template-string.js, test/compress/yield.js, test/mocha/release.js, test/sandbox.js
Required to get the tests green in #209.
Alternatively, version 4 could be the minimum version to build terser, but test runs could still execute on older versions of node.js.
=> Fix #207, drop support for Node versions <4.0.0

.gitignore, .travis.yml, package-lock.json, package.json, test/mocha.js
- Updated prepare and test scripts to be able to run on Windows
- Updated Mocha to 5.2.0 (fixed vulnerabilities alerts)
- Removed Mochallel (it works unstable)
- Added Windows builds to TravisCI
- Updated some other packages
---
Some notes about `mochallel`: his behaviour unpredictable for me, it may work fine or broke 3-4 tests with weird errors. If you insist to use `mochallel`, let's spend time and try to fix it. So, my advise is to use something more stable (like just `mocha` or `mocha-parallel-tests`).
=> Fix prepare and test scripts on Windows

lib/minify.js, test/input/issue-520/input.js
1. The previous regExp may match a map-like string or otherthings before the real inline map, which must in the end of the file. And,
2. The eol in javascript is not only `\n`, but also `\r` `\u2028` `\u2029`, and even no eol before (start of the file).
=> fix `read_source_map` inline bug

lib/parse.js, test/fuzz.js, test/mocha/template-string.js
=> Fix parsing of template literals with an escape

lib/sourcemap.js, test/mocha/sourcemaps.js
Currently, when you specify an original source map prior to compression, the output will only preserve the original sourcesContent if the original source map was a basic one (`BasicSourceMapConsumer`).
If the original source map was an indexed one with sections, such as those potentially output by basic concatenation tooling, the sourcesContent is lost and is always `null` because currently terser is accessing the private `_sources` property and this property is only populated initially for a `BasicSourceMapConsumer` not an `IndexedSourceMapConsumer`.
This PR updates the code to refer to the `sources` public property on the consumer which is implemented for all consumers and, for an indexed source map, returns all the sources from all the sections.
I added a basic test too.
Let me know if …
=> Add support for sections sourcemaps (IndexedSourceMapConsumer)

bin/uglifyjs, test/mocha/cli.js
This pull request deletes the line that spams STDERR with a pointless "using input source map" notification. That information may be relevant in a debugging context, but it should not appear in production code. This is a flaw that carried over from UglifyJS3 and this PR fixes it. Thanks!
=> Remove Spam

lib/compress.js, test/compress/issue-229.js
Fixes https://github.com/terser-js/terser/issues/229
=> fix node.key crashing lib/compress

lib/output.js
When using `max_line_len` empty lines are sometimes output.
I can't really make sense of the structure and functions of this files, so I'm not sure if this is the nicest way of solving the issue. There are so many different ways newlines are printed and so many weird conditionals. But this way does work correctly.
=> stop empty lines being emitted when using max_line_len

tools/terser.d.ts
ref: https://github.com/terser-js/terser#compress-options
=> fix: add missed type defines

lib/transform.js, main.js, main.tests.js, package-lock.json, package.json
bundle.js before: 781kb, after: 776kb
@fabiosantoscode, @nifgraup could you take a look? Actually I'm not sure is it minor or major change according to semver. If this were part of the public APIs, then it should be part of the next major update otherwise it looks like as minor.
=> Exclude APIs required only for tests from main bundle

bin/uglifyjs, lib/ast.js, lib/compress/index.js, lib/minify.js, lib/parse.js, lib/propmangle.js, lib/scope.js, lib/utils.js, main.js, test/run-tests.js, tools/terser.d.ts
Since we're [planning to drop support for running Terser in Node 4](https://github.com/terser-js/terser/pull/271#issuecomment-467666271), and Node 6 fully supports ES2015 Map, we can replace our legacy `Dictionary` class with the native `Map` class. This PR does exactly that.
Breaking changes:
* `Dictionary` has been removed from the main exports. Code relying on `require('terser').Dictionary` will no longer work. I don't think this is too much of a problem: we only really exported it so we could use it to initialize name caches in our own test runner (`test/run-tests.js`).
* `AST_TopLevel.globals`, `AST_Scope.variables` and `AST_Scope.functions` are now `Map`s instead of `Dictionary` objects. Code that consumes Terser's AST may break if they use these properties.
API changes:
* Added a …
=> Replace Dictionary with ES2015 Map

lib/compress/index.js, test/compress/array-constructor.js
Fixes #312. This reverts the previous (incorrect) optimization applied to `AST_New` and instead applies the (correct) optimization to `AST_Call`.
=> fix optimization of `Array` and `new Array`

README.md, lib/ast.js, lib/compress/index.js, lib/minify.js, lib/propmangle.js, test/compress/keep_quoted_strict.js, test/run-tests.js
I made a PR for uglify-js some time back for adding keep_quoted=strict mode which prevents quoted properties from being automatically reserved (which stops unquoted properties of the same name from being mangled). This is much closer to how google-closure-compiler works; it generates less code, more completely obfuscates code and more clearly brings mistakes in code to light. If you mix quoted and unquoted for the same the property with strict-mode, the name mangling will become incorrect and the app will not work correctly, rather than silently fixing it by making any quoted props reserved. It's not as nice, but it's opt-in and for me a more desirable behavior.
Source issue: https://github.com/terser-js/terser/issues/304
@fabiosantoscode I know you said you were busy with Terser 4, but I …
=> add `keep_quoted=strict` mode

test/fuzz.js
Was introduced with ugprade to Acorn 6.1.1.
=> fuzz.js: Ignore an error where Acorn is stricter than Terser at parsing

main.js, main.tests.js, tools/terser.d.ts
In #300, I added a `map_from_object` helper function that's only used by the test runner. Thanks to the refactor in #288, we can now move this function out of the main bundle.
See [my comment on #288](https://github.com/terser-js/terser/pull/288#issuecomment-473603626).
=> Move map_from_object to test-only APIs

lib/compress/index.js
Teeny tiny bugfix. Resolves https://github.com/terser-js/terser/issues/332 to allow for functions added to the Object prototype.
=> Allow for custom funcs on Object.prototype

lib/compress/index.js, test/compress/issue-t292.js
This is the first time I've tried to work on the inner workings of uglify-js / terser. I have some compiler knowledge that helped with understanding the AST and how the compressor works. The solution I came up with to fix #292 does work for my test cases and for the original problem I had, however I can't guarantee it will work for all edge cases. There might also be better ways to solve the problem, but this was the best I could come up with for now. One good thing about how I solved the issue, it only affects the decision about whether to inline / flatten a function, overall working of compression should not be affected other than the cases meeting the conditions where flattening should not happen.
Comments are very welcome :)
=> Compression function inlining/flattening argument/var names colliding with argument values inner scopes

lib/sourcemap.js, test/mocha/input-sourcemaps.js
Currently when `terser` compresses a given input file that comes
with a source-map, but the source-map does not have mappings for
all code parts in the input file. e.g. the input file has been generated
and some specific code-parts have been generated and are not
originating from any source-file.
In that case if mappings before the "generated code" are collected, and
the original file location for the "generated code" is determined after previous
mappings for the same line have been recorded, Terser just ignores the fact that
there is *no original location* and the previous segment is not terminated. This causes
the "generated code" incorrectly to be mapped to the previous segment/
original source location.
=> Fix compressed source-maps have non-terminated segments

lib/mozilla-ast.js, test/mocha/spidermonkey.js
Contrary to the issue I filed, any default parameter (also without destructuring) fails when using the Acorn AST: `function run(x = 2){}`
Compared to the pr #359, this fixes the issue during the AST conversion.
This was unnoticed because `AST_DefaultAssign` generates the same code as `AST_Binary` and the existing test for the spidermonkey AST only tests parsing and re-generating.
Maybe minifying the existing `spidermonkey/input.js` test file would be a better test?
Fixes #358, Closes #359
=> Fix default function params from Acorn AST

README.md
It says class names, when it means function names.
(I'm not sure if I should be updating any version numbers, since this is just a docs change, so I'll refrain from doing so.)
=> Fix typo in `keep_fnames` documentation

lib/output.js, lib/utils.js
I removed `repeat_string` because Nodejs 4 supports native `String.prototype.repeat`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat
=> Use native string repeat

lib/ast.js
Simplified checking for first char without regexp to performance reason.
=> Get rid regexp for checking $

lib/output.js
I refactored checking for nlb without using regexp. It works 3-4x faster in v8 engine.
https://jsperf.com/terser-has-nlb
=> Optimize has_nlb function

lib/ast.js, lib/compress/index.js, lib/minify.js, lib/output.js, lib/parse.js, lib/propmangle.js, lib/scope.js, lib/sourcemap.js, lib/transform.js, lib/utils/first_in_statement.js, lib/utils/index.js, main.js, main.tests.js
It gets rid of one of circular dependency warnings during build.
Based on #376
=> Split utils to separate files

lib/compress/index.js
I cached `self.args_as_names()` before `forEach`. `args_as_names` quite heavy method.
=> Cache args_as_names

lib/ast.js, lib/compress/index.js
I refactored Compress with es2015 class declaration. To improve readability and avoid to legacy inheritance with merging prototypes.
=> Refactored Compress to es6 class

lib/compress/index.js
I got rid of `splice` for replacing array's element.
=> Rewrite element instead of splice

lib/compress/index.js
Fixes bug with `args_as_names is not a function`
=> Fix self.args_as_names error

lib/compress/index.js, test/compress/collapse_vars.js, test/compress/drop-unused.js, test/compress/functions.js, test/compress/reduce_vars.js, test/compress/typeof.js
Fixes #354 
Fixes #294 
Fixes #308
=> Fix issue with reduce_vars

lib/output.js, lib/utils/index.js, test/compress/evaluate.js
Fixed the workaround of V8's RegExp line terminator bug as discussed [here](https://github.com/terser-js/terser/commit/de01b3141ebbfa2ab7ac909ed08725b06eba5f57#r34722043).
The `regexp_source_fix` can be used for both the source of a regex and its `toString`.
=> Workaround for V8's RegExp line terminator bug

README.md, lib/propmangle.js, test/compress/properties.js
This will fix #397 by adding a option of `mangle.properties.undeclared = true`, which is `false` by default to keep backwards compatible.
=> add option mangle.properties.undeclared: boolean

README.md
* Show the GH sanitized SVG. Usually the MIME Content-Type returned is `text/plain` instead of the wanted `image/svg+xml`
Needs:
* Ideally should constrain this with HTML `width` and `height` `img` tag instead of markdown so it's not hugely wide with Xthexder's Wide Github userscript unless it is not minded. Completed in 96578057e1bb4f9564bec4c31d5b20c37cdd035a
Note:
* Trailing white-space omitted by my editor automatically... hope this isn't an issue. Most of the time it isn't.
Refs:
* https://github.community/t5/How-to-use-Git-and-GitHub/Embedding-a-SVG/td-p/2192
Post #415
=> Fix Content-Type return for SVG logo usage on GH

CHANGELOG.md, README.md, lib/compress/index.js, package.json, test/compress/issue-t120.js, test/compress/reduce_vars.js
terser's github org name is no longer "terser-js". This PR changes all instances of the old name for the new one (just "terser").
=> refactor: update the org name

lib/minify.js, test/mocha/sourcemaps.js, tools/terser.d.ts
Fixes #278 
Same approach which was discussed, adding `sourceMap.asObject` will return the source map as an object.
@fabiosantoscode Let me know if any changes are needed
=> Add option to return source-map as object

tools/terser.d.ts
`max_line_len: false | number` is a correct type for the current code.
I think `max_line_len: number` (default: `Infinity`) is more natural ([kei-ito/terser/commit/119bd09](https://github.com/kei-ito/terser/commit/119bd09f8731fff254e3b8b0c731d87fb46e8fd9)). But it is imcompatible with UglifyJS.
=> fix the type of OutputOptions.max_line_len

lib/output.js, test/compress/comments.js
Default value for --Coments now is `'some'`, comments that include `/*!` will also be preserved...
=> Fixes #438, Modify default --Coments value

README.md, bin/terser, test/input/issue-483/input.js, test/mocha/cli-2.js
Make sure that regex nodes are correctly parsed into RegExp option as per README.
Fixes #483.
=> Fix regex parsing in CLI

README.md
Thought that the text should say **end** rather than _start_, as `$` denotes end-of-string rather than the beginning.
=> [Docs] Correct regex documentation example for property mangling

lib/scope.js, test/mocha/minify.js
=> improve error messages

README.md
Terser preserves _some_ comments by default. Fixed #520.
=> docs: fixed default value for `comments` option

lib/parse.js
I just optimized condition. if `is_surrogate_pair_head` it can't be `tail`
=> Optimize condition for full char

lib/parse.js
Since seems to be used with string lengths only, a `val < 0` isn't possible. Loop will end at `0` naturally. Since the current code is using `i--` (vs `--i`), if `i === 0` initially, the while loop won't run. If a number `< 0` is expected, I'd propose checking before the loop vs each iteration.
```js
// current
while (i-- > 0) // ...
// proposed
while (i--) // ...
```
=> Remove extra comparison in while loop

lib/output.js, lib/parse.js
I refactored function `is_surrogate_pair_head` and `is_surrogate_pair_tail` to use only one type argument.
string or number. (no good for v8 optimization)
=> Optimize checking surrogate pair

lib/compress/index.js, test/compress/conditionals.js, test/compress/if_return.js, test/compress/transform.js
I frequently write separated if-statements-with-return, even if the consequents are the same:
```js
if (foo) {
return null;
}
if (bar) {
return null;
}
```
This is mainly to add ample comments above each if-statement. Having these join together into `foo || bar` ternarys should be a win if the consequents are large.
=> Collapse multiple if-statements with the same consequents

lib/ast.js
This makes console.log() and similar tooling print the right type for
the class.
=> Set AST_Node.prototype.constructor.

tools/terser.d.ts
- `SourceMapOptions.content` can be source map object,  `'inline'` or source map file content according to documentation and [tests](https://github.com/terser/terser/blob/6ba84bc30a231ba94a844c2ac43821123add6b64/test/mocha/sourcemaps.js#L153)
=> Fix typing for SourceMapOptions.content

README.md, lib/compress/index.js, test/compress/unsafe_symbols.js, tools/terser.d.ts
Since I suggested this in #580, I decided to take a stab at implementing it as it seemed simple enough. That being said, with absolutely no familiarity with this code-base, I'm going to need some pointers.
With this, the following code:
```
const SYMBOL_DOG = Symbol("kDog");
const SYMBOL_CAT = Symbol("kCat");
console.log(SYMBOL_DOG, SYMBOL_CAT);
```
Is optimized into this:
```
const SYMBOL_DOG=Symbol,SYMBOL_CAT=Symbol;console.log(SYMBOL_DOG,SYMBOL_CAT);
```
This is *almost* correct, but the lack of parenthesis is an error because `Symbol` is a native constructor. I'm not sure how to resolve that, so I could use a pointer!
Additionally, I'm 70% sure that my use of passing `exp` directly as the `props` parameter for `make_node` is actually wrong, but again I'm not familiar with this at all. …
=> Implement `unsafe_symbols` optimization

lib/compress/index.js
before `value.contains_this()` could be called for `AST_Lambda` or `AST_Class` but method itself defined only for `AST_Lambda` and attemp to call it on `AST_Class` cause terser to crash
Closes #593
=> fix: call "contains_this" only for AST_Lambda

bin/terser, test/input/issue-585/input.js, test/mocha/issue-585.js
As described in #585 setting the CLI argument `--comments` to `false` results in unexpected behaviour since the non-empty string `'false'` gets passed as a string and later gets evaluated to `true`.
I added an mocha test case for this issue and fixed it.
=> Fixed issue #585 (Problem with setting --comments to false)

lib/compress/index.js, test/compress/template-string.js
This adds support for template literals inside `+` binary operations. Our babel transforms aren't always the smartest when outputting code, so we'll sometimes get ``` `foo ${expression} bar` + 'baz' ``` expressions that can be joined into a single ``` `foo ${expression} barbaz` ```
=> Optimize template literals in binary expressions

test/compress/template-string.js
Re: https://github.com/terser/terser/pull/633
This adds explicit tests for joining template literals with strings that chars with special meaning inside template literals. Mainly to ensure I didn't just add a security vulnerability.
=> Add explicit tests for template literal joining with special chars

package.json
Terser is a minifier for ES6 so it would be nice to provide an option to import it as an es module. This PR adds an es module output to the rollup configuration. With this change terser can be imported directly into a web browser!
=> es module build for browser

README.md, bin/terser, lib/ast.js, lib/compress/index.js, lib/parse.js, lib/scope.js, lib/size.js, test/compress.js, test/compress/block-scope.js, test/compress/collapse_vars.js, test/compress/drop-unused.js, test/compress/inline.js, test/compress/issue-t292.js, test/compress/reduce_vars.js
I believe I've improved some aspects of inlining. It became a bit simpler than before. Also, inlining something updates more scope of the parent scope's information than before, fixing #639.
My original goal was to make it so new, unique variable names were always created, and checking for collisions didn't need to happen, but it turns out that generating new names didn't fix all the problems, and people would probably be upset or confused if their variable names were changed without them using the mangle option.
Then I tacked on a change I was interested in, which was to start measuring symbols differently depending on whether mangling was enabled, fixing #321.
=> Improve inlining

.travis.yml, lib/parse.js, test/compress/numbers.js
Adds support for [Stage 3 Numeric Separators](https://github.com/tc39/proposal-numeric-separator).
Numeric separators are available in V8, SpiderMonkey, JavaScriptCore and ChakraCore (see [here](https://github.com/tc39/proposal-numeric-separator/issues/43#issue-426539288)).
Considerations:
- As a stage 3 feature does this need special treatment, such as a flag?
- I notice that class fields do not
- How far should terser go to ensure parse-correctness? This currently "allows" the following, which could be caught with additional logic:
- `1_e_1`
- `0_x_123`
Fixes #632
=> Add numeric separators support

.ls-lint.yml, package-lock.json, package.json
Hey @fabiosantoscode,
added [ls-lint](https://github.com/loeffel-io/ls-lint) as discussed. 
Just let me know if you are happy with the current configuration: 
```yaml
ls:
'{lib,tools,test}':
.js: kebab-case
.ts: kebab-case
.d.ts: kebab-case
.html: kebab-case
.json: kebab-case
ignore:
- test/input
- test/compress
- lib/utils/first_in_statement.js
```
Merge of the [terser-functional-tests pr](https://github.com/terser/terser-functional-tests/pull/103/files) is required
=> add ls-lint

tools/terser.d.ts
Resolves #777 
- Removed `AST_Node` references
- Changed `comments(node, comment)` option so `node` is an any
- Removed `ast` property from `MinifyOutput`
- Removed `async` modifier
=> fix typings

package.json
Hi! Super excited that v5 supports ESM!
[Rollup doesn't yet support `pkg.exports`](https://github.com/rollup/plugins/issues/362). If I want rollup to include terser in my bundle (without commonjs shims), then the `module` field is needed in `package.json`. So now if I make a rollup bundle with this:
```
import {minify} from 'terser'
...
```
Then terser will get added correctly to my bundle.
=> Add `module` to package.json

tools/terser.d.ts
Although `output` option is deprecated, it still works. TypeScript 4 supports the `@deprecated` jsdoc flag, which will identify the field as deprecated in the IDE
Fixes #835
=> Add @deprecated output field to MinifyOptions type

package.json
Currently this shows error terser@5.3.6: The engine "node" is incompatible with this module. Expected version "^10.0.0,^11.0.0,^12.0.0,>=14.0.0". Got "12.18.4"
Closes: https://github.com/terser/terser/issues/854
=> fix: fix incorrect node engine semver versions

package.json
Per https://github.com/terser/terser/issues/858#issuecomment-713003583
Specifically, the string form always works; the array fallback to the string form is necessary for node v13.0-v13.1; for node v13.2-v13.6, the object form has to have "default", or else you need the string fallback.
=> fix: ensure "exports" works on all versions of node

rollup.config.js
repo: [ycjcl868/jest-terser-oom](https://github.com/ycjcl868/jest-terser-oom)
ref: https://github.com/facebook/jest/pull/10534, https://github.com/webpack-contrib/terser-webpack-plugin/issues/143
Close: https://github.com/terser/terser/issues/164#issuecomment-725313998
If I removed the `sourceMappingURL`, the test case passed or caused out of memory.
If  I removed the `domprops`, the test case passed too.
=> fix: sourcemap inline dist code, caused jest oom

lib/cli.js, test/mocha/cli-2.js, test/mocha/cli.js, test/mocha/release.js, tools/terser.d.ts
Hi. Tests are passing and I think everything is ok here. The beautify functionality was only removed for CLI. Why not entirely? Because you use it with tests.
Closes #214
=> Remove the beautify option

lib/ast.js, lib/output.js, lib/parse.js, lib/scope.js, lib/size.js, test/compress.js, test/compress/class-properties.js, test/compress/classes.js
=> Private fields and methods support 

test/compress/classes.js
This is a followup to https://github.com/terser/terser/pull/913. @robpalme suggested that we test accessors as we've seen other projects handle them sub-optimally: thankfully terser seems to be ok with them!
=> Test private fields as accessors

tools/domprops.js
Add `exports` attribute to domprops.js
See: https://webassembly.github.io/spec/js-api/#dom-instance-exports
=> domprops.js: add `exports`

package.json
We have code that relied on `require.resolve` to properly respect the path we provide it https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/terser/index.js#L166
However, under Node 12/14, `require` will respect `exports` over what we were relying on. Per the docs, NodeJS recommends exposing old paths to avoid being breaking by accident
```
Warning: Introducing the "exports" field prevents consumers of a package from using any entry points that are not defined, including the package.json (e.g. require('your-package/package.json'). This will likely be a breaking change.
To make the introduction of "exports" non-breaking, ensure that every previously supported entry point is exported. It is best to explicitly specify entry points so that the package’s public API is well-defined. …
```
=> fix: add backwards compatible change for require.resolve

README.md, lib/minify.js, test/mocha/spidermonkey.js
This commit adds a `spidermonkey` option, similar to the CLI, to the `minify` API.
`spidermonkey` is a shortcut for setting that option as both a `parse` and `format` option.
These options, defaulting to false, when set to true, result in accepting and/or producing a Spidermonkey (Mozilla, ESTree) AST.
Closes GH-973.
//cc @fabiosantoscode
=> Add `spidermonkey` options to `minify`

lib/equivalent-to.js, test/compress/issue_1014.js, test/compress/issue_999.js
`AST_DotHash#shallow_cmp` was never implemented so equality checks for private element access were using the comparison function from the super (`AST_PropAccess`) class. With these changes we compare private element access expressions by private name.
Fixes #1014.
Fixes #999.
=> fix: private class element access equality

lib/compress/index.js, test/compress/issue-1006.js
Fixes #1006 
----
I've been running into the same issue as #1006 while trying to minify my app's vendor code chunk via webpack5 (after upgrading from webpack4) and using its vanilla optimization config in production mode.
```
ERROR in vendor.js from Terser
TypeError: Cannot read property 'option' of undefined
at AST_SymbolRef.may_throw_on_access (/home/basti/repos/streamlink-twitch-gui/node_modules/terser/dist/bundle.min.js:12979:28)
at AST_Dot.has_side_effects (/home/basti/repos/streamlink-twitch-gui/node_modules/terser/dist/bundle.min.js:13918:50)
at is_undefined (/home/basti/repos/streamlink-twitch-gui/node_modules/terser/dist/bundle.min.js:12971:33)
at /home/basti/repos/streamlink-twitch-gui/node_modules/terser/dist/bundle.min.js:15552:12
at AST_VarDef.optimize …
```
=> fix: missing compressor arg in optimize AST_VarDef

README.md, tools/terser.d.ts
This patch updates the documentation to explain the existing `enclose` option, and also modifies the type definition of `MinifyOptions` to accept the `enclose` field.
Related lines of code: https://github.com/terser/terser/blob/d3d924fa9e4c57bbe286b811c6068bcc7026e902/lib/minify.js#L186-L188 https://github.com/terser/terser/blob/d3d924fa9e4c57bbe286b811c6068bcc7026e902/lib/ast.js#L448-L451
=> Documentation and type definition: MinifyOptions.enclose

README.md
Two small corrections to documentation for `keep_fnames` option.
=> Fix 2 typos in README for `keep_fnames` option

lib/compress/inference.js, test/compress/issue-1003.js, test/compress/issue-1007.js
This PR does 2 things:
- It removes special casing for nullish coalescing (??) in negation
- This fixes #1003
- We also made sure optional chaining (?.) is ok
- This cements #1007 as fixed
=> Fix nullish coalescing negation inference

RECIPES.md
I wrote some code that allows using the 'terser' plugin in the 'gulp' build.
There is no longer any need to use additional plugins for this.
=> Terser for Gulp

lib/compress/index.js, test/compress/functions.js, test/compress/issue-1750.js, test/compress/reduce_vars.js, test/compress/switch.js
This implements:
1. Full case folding for equivalent branches
2. Full removal of empty tail branches (even when `default` isn't last branch, as long as `default` falls through to the empty tail)
3. Converts 1-case switches into an If statement
4. Converts 2-case switches into an If-Else statement
5. Folds side-effect free case expressions into default (when there are no side-effect case expressions after them)
6. Full Switch removal when all cases are "default"
The Switch removal is hard to describe, but easy to demonstrate:
```js
switch (expression) {
case 1:
case 2:
case 3:
default:
doSomething();
}
```
Because all of the case `expression`s are side-effect free, we can consider just the case bodies. Because all cases fall through to the last branch, we can check to see if this branch is …
=> Optimize various switch statements

README.md, lib/compress/index.js, lib/minify.js, lib/propmangle.js, lib/scope.js, test/compress.js, test/compress/properties.js, test/compress/rename.js, tools/terser.d.ts
Adds a new option to `options.mangle` and `options.mangle.properties` called `nth_identifier` that allows the caller to completely replace the implementation of `base54`, e.g. to provide identifiers in a particular order, ban certain identifiers, etc.
It is required to be a function with one of the following two interfaces:
```ts
/**
* An identifier mangler for which the output is invariant with respect to the source code.
*/
export interface SimpleIdentifierMangler {
/**
* Obtains the nth most favored (usually shortest) identifier to rename a variable to.
* The mangler will increment n and retry until the return value is not in use in scope, and is not a reserved word.
* This function is expected to be stable; Evaluating get(n) === get(n) should always return true.
* @param n The ordinal …
```
=> Support mangle.nth_identifer to customize base54 behavior

README.md, lib/compress/index.js, test/compress/arrays.js
Only simple case `Array.from(array)` -> `array`
Closes #746
=> Added Array.from unsafe optimization

lib/ast.js, lib/minify.js, lib/output.js, lib/propmangle.js, test/compress.js, test/compress/class-properties.js, test/compress/issue_1014.js, test/mocha/sourcemaps.js
This fixes an error with private getter/setters being mangled as if they were regular public properties:
```js
export class Foo {
get #aaaaaa() {}
constructor() {
this.#aaaaaa
}
}
```
In this, `get #aaaaaa {}` is a `AST_PrivateGetter`, which isn't a subclass of `AST_ClassPrivateProperty` nor `AST_PrivateMethod`. But it is a subclass of `AST_ObjectProperty`. So our property mangler was mangling the key as if it were a public property, and not consulting the `private_cache` mapping. So the mangler renames the getter to `#o` and the access to `#a`:
```js
class Foo {
get #o() {}
constructor() {
this.#a;
}
}
```
This also enables private property mangling by default whenever we're doing a normal mangle pass. This is as safe as mangling regular `const variable_name = 1`, because private …
=> Fix private getter/setter mangling

lib/transform.js, test/compress/class-properties.js
We forgot to define the transform function for `AST_DotHash`. Since it's the same as `AST_Dot`, I opted to share on the base `AST_PropAccess` class and just list `AST_Sub` define it's own special transform.
Fixes #1067.
=> Fix mangling nested dothash expressions

lib/compress/index.js, lib/propmangle.js, test/compress/mangleprops-computed.js, test/compress/mangleprops-strict-computed.js, test/compress/mangleprops-strict.js, test/compress/mangleprops.js, test/mocha/minify.js
There were various failures when using computed properties with property mangling enabled with `keep_quoted`:
```js
// keep_quoted: true
let prop = '_foo';
let o = {
[prop]: 'bar'
};
console.log(o[id('_foo')]);
// - - -
let prop = '_foo';
let o = {
[prop]() { return 'bar' }
};
console.log(o[id('_foo')]());
// - - -
let prop = '_foo';
let o = {
get [prop]() { return 'bar' }
};
console.log(o[id('_foo')]);
```
```js
// keep_quoted: 'strict'
let prop = '_foo';
let o = {
[prop]: 'bar'
};
console.log(o[id('_foo')]);
```
=> Don't mangle computed properties with keep_quoted

lib/compress/tighten-body.js, test/compress/collapse_vars.js
Fixes https://github.com/terser/terser/issues/1033
=> collapse_vars: fix inlining expr into scope with shadowed var

lib/minify.js
While the test cases work, actually attempting to use the `nth_identifier` feature in a downstream project encountered a `DefaultsError: nth_identifier is not a supported option`.
Testing with a monkey patch showed that adding the missing default value fixes the issue.
=> Fix missing nth_identifier default in minify()

lib/compress/index.js, test/compress/expansions.js
The two cases forgot to backtrack, so the following property was not being inlined.
=> Fix inlining object spread properties

lib/compress/index.js, test/compress/inline.js
This fixes #1046 . I also added a simple test case to `tests/compress/inline.js` to verify it.
=> fix: functions may be compressed mistakenly if passes=2

lib/propmangle.js, test/mocha/minify.js
This fixes a bug when an original property (`obj.i`) shares the same name as a mangled property (`obj.prop` -> `n.i`), and you're using a name-cache. Because our mangled name collides, we have to ensure all original `.i` properties are renamed to something else (`n.o`).
But, because we had a name-cache, we would reserve the mangled property name in the mangler. That prevents us from attempting to rename the original `.i` property to `.o`.
Fixes https://github.com/terser/terser/issues/233.
=> Fix collisions between original property and mangled property

lib/compress/drop-side-effect-free.js, lib/compress/evaluate.js, lib/compress/index.js, lib/compress/inference.js, test/compress/drop-unused.js, test/compress/evaluate.js
This implements the recursion necessary to determine if a property access/call is part of an optional chain that has short-circuited.
Fixes https://github.com/terser/terser/issues/1040
=> Fix compress/eval of optional chains

lib/compress/index.js, test/compress/switch.js
This is an additional optimization that leverages changes from #1044 @jridgewell 
Current code does not **fully optimize** the following code:
```js
switch (_var) {
case 1: return true;
case 2: return true;
case 3: return false;
case 4: return true;
case 5: return false;
case 6: return false;
case 7: return true;
case 8: return true;
}
```
The current output returns something like this:
```js
switch (_var) {
case 1: case 2: 
return true;
case 3: 
return false;
case 4:
return true;
case 5: case 6: 
return false;
case 7: case 8: 
return true;
}
```
The expected output in this case should be:
```js 
switch (_var) {
case 1: case 2: case 4: case 7: case 8: 
return true;
case 3: case 5: case 6: 
return false;
}
```
------------------------
Adding a default case can benefit the optimization even …
=> collapsing switch cases with same bodies, when not lined in a row

lib/compress/index.js, test/compress/dead-code.js
=> Keep iife assignment in return statement for async/generators

lib/scope.js, test/compress/export.js
In some cases, it's possible to generate a collision between an exported variable declaration (which cannot be mangled) and a local reference. Eg,
```js
// input
const n = null;
export const o = {o: n};
// options:
{ module: true, reduce_vars: false }
// output
const o=null;
export const o={o:o};
```
=> Fix a collision with exported variables with short names

lib/compress/index.js, test/compress/nullish.js
Fixes https://github.com/terser/terser/issues/1102
=> Fix delete on optional chain

lib/output.js
The old max_line_len code fell into a surprising slowdown where repeatedly inserting chars in the middle of a string falls into O(n^2) behavior. Surprising because V8 already implements advanced data structures for string slicing and joining (`SlicedString` and `ConsString`). It seems like this should be easily handled by the two.
Anyways, we avoid this by slowing building a committed string (which is unlikely to be changed). Whenever we insert, we commit the left hand side, and can avoid slicing it in the future.
In testing a 5mb file (done by repeating a program several times), I dropped the simple parse+output case from 5min to 5sec.
Fixes https://github.com/terser/terser/issues/374.
=> Optimize max_line_len

README.md, lib/output.js, test/compress/comments.js
This implements https://github.com/terser/terser/issues/1151 so that comments containing `@copyright` are treated the same as those with `@license` as part of the default `--comments some` behavior.
=> Preserve @copyright comments as part of "some" default

package-lock.json, package.json
`source-map@0.7.3` has an issue with buggy identification of node vs browser environment (it uses `typeof fetch === 'function'` to spot browsers) - See https://github.com/mozilla/source-map/issues/349, https://github.com/mozilla/source-map/issues/432 and fixes https://github.com/mozilla/source-map/pull/350, https://github.com/mozilla/source-map/pull/363.
This is an issue for React (Native) environments where `fetch` is often polyfilled, eg for testing or SSR. It's one of the last issues holding us back from making `terser` the default minifier for https://github.com/facebook/metro.
Importantly, this is also **probably going to be an issue for all NodeJS users soon**, as NodeJS moves forward with a native global `fetch`: https://github.com/nodejs/node/pull/41749
Unfortunately, the only …
=> Update source-map -> 0.8.0-beta.0 for compatibility with global `fetch`

lib/ast.js, lib/equivalent-to.js, lib/mozilla-ast.js
Remove all the places where code is built as a string and then evaled to make a function. This improves compatibility with runtimes where eval is banned.
The codeshift does the minimal set of changes to make this work, and I have manually fixed a couple of things after running the codeshift.
* Fix the DEFNODE function for the new param order.
* Remove the map/mkshallow functions.
The source for the codeshift is here: https://github.com/sgoo/ast-fixer
I did have a go at replacing the calls to DEFNODE with `class` declarations, I got the code to run, but I got test failures where the minified output was slightly wrong, I'm not sure what caused that.
My results from that attempt are here: https://github.com/sgoo/ast-fixer/commit/f77472eeb89b96925034d43f305203e642f099b3
Fixes #925
=> Run Eval removing codeshift

lib/propmangle.js
This is treated as an eval call by V8, and can't be executed in environments where eval is blocked.
Fixes #925
=> Remove last new Function() call

package.json
See https://github.com/microsoft/TypeScript/issues/47792#issuecomment-1043819482
otherwise, building with nodenext resolution results in:
```
.yarn/__virtual__/terser-webpack-plugin-virtual-7ea69a4a8a/2/.yarn/berry/cache/terser-webpack-plugin-npm-5.3.1-0c0596f996-9.zip/node_modules/terser-webpack-plugin/types/index.d.ts:116:39 - error TS7016: Could not find a declaration file for module 'terser'. '/home/lizf/.yarn/berry/cache/terser-npm-5.7.2-c24448e930-9.zip/node_modules/terser/dist/bundle.min.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/terser` if it exists or add a new declaration (.d.ts) file containing `declare module 'terser';`
116 declare class TerserPlugin<T = import("terser").MinifyOptions> {
~~~~~~~~
.yarn/__virtual__/terser-webpack-plugin-virtual-7ea69a4a8a/2/. …
```
=> include types export for ts4.7 nodenext resolution

package.json
The ordering of types vs import is specific according to the documentation.
=> Fix #1193 to work properly

lib/compress/evaluate.js, lib/compress/index.js, test/compress/evaluate.js
Given the input `a.b.c.d.e.f`, the previous code would call `_eval` 57 times when using `unsafe` (and 15 times when using normal):
```
1 a.b
2 a.b.c
3 a.b
4 a.b
5 a.b.c.d
6 a.b.c
7 a.b
8 a.b
9 a.b.c
10 a.b
11 a.b
12 a.b.c.d.e
13 a.b.c.d
14 a.b.c
15 a.b
16 a.b
17 a.b.c
18 a.b
19 a.b
20 a.b.c.d
21 a.b.c
22 a.b
23 a.b
24 a.b.c
25 a.b
26 a.b
27 a.b.c.d.e.f
28 a.b.c.d.e
29 a.b.c.d
30 a.b.c
31 a.b
32 a.b
33 a.b.c
34 a.b
35 a.b
36 a.b.c.d
37 a.b.c
38 a.b
39 a.b
40 a.b.c
41 a.b
42 a.b
43 a.b.c.d.e
44 a.b.c.d
45 a.b.c
46 a.b
47 a.b
48 a.b.c
49 a.b
50 a.b
51 a.b.c.d
52 a.b.c
53 a.b
54 a.b
55 a.b.c
56 a.b
57 a.b
```
The first optimization is to only call `expression._eval(…)` a single time per evaluation of a `AST_PropAccess`. We've already called it to determine if we're a nullish, so there's no …
=> Optimize property access evaluation

lib/output.js, test/compress/issue-143.js
Very minor change, just a couple of typos fixed, no logic changes.
=> chore: fixed a couple of typos

lib/compress/tighten-body.js, test/compress/issue-1248.js
fix https://github.com/terser/terser/issues/1248
=> fix: incorrect `to_simple_statement`

lib/parse.js, test/compress/syntax-errors.js
Fix Issue #1011 
I don't know if I add test case in the correct place. Maybe I should put the test case in `test/compress/issue-1011.js`?
=> fix: throw error when using private field in an object (#1011)

test/compress/concat-strings.js, test/compress/template-string.js
There is a small typo in test/compress/concat-strings.js, test/compress/template-string.js.
Should read `concatenation` rather than `concatentation`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, concatentation -> concatenation

tools/terser.d.ts
Aligning the TS definition for source map option with the docs:
https://terser.org/docs/api-reference#source-map-options
=> fix: add asObject to SourceMapOptions definition

CONTRIBUTING.md
This PR removes extraneous `)` in `CONTRIBUTING.md` to fix the link.
=> Remove extraneous `)` in CONTRIBUTING.md

lib/ast.js, lib/mozilla-ast.js, lib/output.js, lib/parse.js, test/compress/export.js, test/mocha/spidermonkey.js
In this PR we implement the support of ES2022 string module names and ES2020 `export * as ns`. These two features are highly related so it end up in a single PR.
- AST changes: `.quote` is introduced to `AST_SymbolImportForeign`, `AST_SymbolExportForeign` and `AST_SymbolExport`. It will be `"` or `'` if the module name is a string, otherwise it is `undefined`. I am not sure if we want to stick with the `AST_Symbol` prefix now that it can be a string, too. Anyway I will wait for more feedback before any drastic AST change
- Added new parser method `as_symbol_or_string` to handle `export * as "f-oo"`
- Added specific handling to differentiate between `import { * as foo }` and `import { "*" as foo }`
The parser currently do not validate that module names should be a valid UTF16 string (no …
=> Support string module name and export * as

lib/minify.js, test/mocha/no-mutate-input.js
Writes `source_map`, `_destroy_ast`, etc, to a shallow copy of the `options.format || options.output` object. This allows an `options` object to be reused safely in multiple `minify` calls, without subsequent calls clobbering earlier results.
Fix: #1341
=> Don't mutate options object. Fixes #1341

lib/ast.js, lib/compress/index.js, lib/compress/reduce-vars.js, test/compress/reduce_vars.js
#1338 revealed that fixing fixed values where Defun is involved made a lot of code larger!
This attempts to fix it where possible. Terser doesn't have flow analysis, but it can tell if the Defun in question was referenced before a certain variable exists.
So that's the fix here. If `func_name` is found before `used_in_func`, `fixed` disappears.
=> close #1338 where possible 

CHANGELOG.md
Hi! It appears that the changelog is incorrectly referring to a version v5.16.7 which hasn't been released. If I understood correctly, the intention was to add changelog entries for v5.16.6 but that one was skipped by accident ☺️
=> Fix version number in CHANGELOG.md

README.md, lib/ast.js, lib/parse.js, lib/propmangle.js, lib/utils/index.js, test/compress/mangleprops-key-annotation.js
Here I add a new annotation `@__KEY__`  that when placed before a string literal causes it to be mangled like a property.
Example:
```js
function lookup(object, key) {
return object[key]
}
let result = lookup({ somekey: 5}, /*@__KEY__*/ "somekey") 
console.log(result) // prints 5 even if somekey was mangled
```
Do you think this should be part of Terser? Are you happy with the annotation name?
I'm leaving the readme and tests until it is decided that this is a useful feature...
=> Add @__KEY__ annotation to mangle string literals

lib/ast.js
I noticed that in some rare cases, Terser does not mangle a `@__KEY__` annotated string literal.
I traced this to the annotations not being copied in the AST_String constructor.
It is not clear to me when Terser decides to clone a node, so I wasn't able to construct a minimal test case for this. But testing on a real code-base showed that this change does fix the issue.
=> @__KEY__: Correctly copy annotations when cloning AST_string

lib/mozilla-ast.js
I removed needless check for `in_directive`. It is not necessary because after `in_directive = false;` all code inside `for` is not reachable.
=> Simplify normalize directives

lib/mozilla-ast.js
Minor fix. I've removed needless wrapper for `map`.
=> Remove needless wrapper for from_moz

lib/ast.js, lib/compress/drop-side-effect-free.js, lib/compress/drop-unused.js, test/compress/drop-unused.js
Closes [#1472](https://github.com/terser/terser/issues/1472)
This is a new way to close the issue, that's both slightly safer and simpler to understand.
=> improve handling of self-referential classes

lib/compress/index.js, test/compress/expansions.js
This is a follow-up to 6f04338 (#1004)
Note, as I said in #1004, I have not yet found where in the spec it says how spreading constants other than `undefined` & `null` should be handled.
=> object spread: also drop non-nullish constants (e.g. `{ ...true }`)

tools/domprops.js
`unadjustedMovement` is an option of the [`element.requestPointerLock()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock#unadjustedmovement) api.
```js
canvas.requestPointerLock({
unadjustedMovement: true,
});
```
It is not widely supported though and on MDN it's still flagged as non-standard. But I'm not sure what the requirements are for something to be added to domprops.
=> Add unadjustedMovement to domprops

lib/output.js
In the case of this code snippet:
```js
const myFunction = (callback = () => {}) {
callback();
}
```
Terser would insert parenthesis in the default parameter like this:
```js
const myFunction = (callback = (() => {})) {
callback();
}
```
They aren't needed, so don't generate them.
=> Don't add parens when arrow function is part of a default assign

lib/mozilla-ast.js, test/compress.js, test/compress/big_int.js
When working with [ESTrees](https://github.com/estree/estree) (a.k.a. Mozilla/SpiderMonkey ASTs), Terser assumes that bigint literal objects have the following shape:
```
type: "BigIntLiteral",
value: 123n,
```
However, "BigIntLiteral" is just the name of ESTree's internal canonical interface, not the value of the `type` property. [Looking at the specification](https://github.com/estree/estree/blob/master/es2020.md), bigint literals instead have the following shape:
```
type: "Literal",
value: 123n,
bigint: "123",
```
This PR updates the code to match the behavior from the spec and to be compatible with other ESTree-producing/consuming tools.
=> Fix incorrect bigint literal conversion to/from ESTree

lib/compress/evaluate.js, test/compress/typeof.js
Partialy resolved: #250.
Only fixs `typeof`, because `instanceof`'s behavior is unsafe to be determined on compile time. (E.G. We can use `Symbol.hasInstance` to override)
=> Allow `typeofs` to evaluate typeof on object and array

lib/compress/common.js, lib/compress/reduce-vars.js, test/compress/issue-1338.js, test/compress/issue-1429.js, test/compress/reduce_vars.js
Fixes #1429 
This allows variables to be reduced when used in a function that has indirect calls.
I'm new to terser so it might have bugs.
Benchmark result:
| url                                                                                | input size | before output size | after output size | size diff     | before time | after time | time diff |
| ---------------------------------------------------------------------------------- | ---------- | ------------------ | ----------------- | ------------- | ----------- | ---------- | --------- |
| https://code.jquery.com/jquery-3.2.1.js                                            | 268039     | 86877              | 86877             | 0             | 674.72494   | 672.01946  | -0.40%    |
| …
=> reduce variables when functions have indirect calls

lib/cli.js, test/mocha/cli.js
Resolves #962
Happy to add tests for this, but I didn't see any existing tests for the `--output` CLI option; am I missing them?
=> Ensure parent directory exists when using --output on CLI

lib/compress/evaluate.js, test/compress/expansions.js
E.g. previously it would return `false` for expressions like `void !0`
=> make `is_constant()` recognize constants with several unary prefixes

lib/compress/index.js, test/compress/drop-console.js
The current `drop_console` implementation only removes direct console method calls (e.g. `console.log()`) but fails to remove chained method calls like `console.log.apply()`.
=> fix: correctly remove the console methods when drop_console is an array

lib/compress/compressor-flags.js, lib/compress/index.js, test/compress/issue-1545.js
This pull request addresses Issue #1545 in the Terser project, which involves removing unnecessary `console.assert` calls from the codebase. Specifically, this PR removes `console.assert` calls with expressions that are always true, ensuring that only relevant assertions remain in the code.
- Removed `console.assert(true, ...)` and `console.assert(1, ...)` calls, as they don't serve any purpose.
- Kept `console.assert(false, ...)` and `console.assert(0, ...)` calls, as these might be valuable for debugging.
- The test for Issue #1545 has been updated and successfully passes with the expected output.
- Closes #1545
=> Solving issue-1545

README.md
Use `unsafe_comps` when comparison of number and not a number is unsafe:
```js
(NaN>=1?"yes":"no") !== (1>NaN?"no":"yes")
```
=> Add notice for unsafe_comps about NaN

lib/mozilla-ast.js, test/mocha/spidermonkey.js
When const assignents are inlined into subsequent expressions, the const declaration were not removed during minifcation in module mode, causing an invalid, unitialized const declaration to be emitted.
Per original spidermonkey specification [1] and estree, the variable declaration `kind` (var, const, let) is not defined in `VariableDeclarator` [1] nodes, but in its parent node `VariableDeclaration` [2]:
```
Node {
type: 'VariableDeclaration',
declarations: [
Node {
type: 'VariableDeclarator',
id: …
init: …
}
],
kind: 'const'
}
```
The AST converter tried to read `kind` from `VariableDeclarator`, where it is never supplied, causing invalid terser AST: `AST_Const` was combined with `AST_VarDef` instead of `AST_SymbolConst` nodes:
```
AST_Const {
definitions: [
AST_VarDef {
name: …
```
=> Fix unitialized const declaration when minifying from spidermonkey ast

lib/ast.js, lib/compress/common.js, lib/compress/drop-unused.js, lib/compress/index.js, lib/compress/inference.js, lib/compress/reduce-vars.js, lib/compress/tighten-body.js, lib/equivalent-to.js, lib/mozilla-ast.js, lib/output.js, lib/parse.js, lib/scope.js, lib/size.js, lib/transform.js, package-lock.json, package.json, test/compress/class-properties.js, test/compress/sequences.js, test/compress/unicode.js, test/compress/using.js, test/input/spidermonkey/input.js, test/mocha/size.js, test/mocha/spidermonkey.js
Fixes https://github.com/terser/terser/issues/1625.
This PR is a very preliminary support for the using / await using declarations. The priority of this PR is to parse such declarations and ensure that we don't drop/inline such declarations in the optimizer: Because unlike const declarations, a `using` declaration itself, even unused, typically has side effects. Therefore this PR will surely miss quite a few optimization opportunity, which I think should be addressed in the future.
```ts
interface Using extends Definitions {
definitions: UsingDef[]
}
interface AwaitUsing extends Definitions {
definitions: UsingDef[]
}
interface UsingDef {
name: AST_SymbolUsing|AST_SymbolAwaitUsing
value: AST_Node?
}
```
Unlike `var`, `let` and `const`, we provided a new interface `UsingDef` for the …
=> Support `using` and `await using` declarations
